[settings]
# It must be int.
interval = 30 # second, the interval between check
after = 300   # second, the interval after find signature

[location]
lng = 113.398469
lat = 23.038849

[logging]
level = INFO
console = false # show in console
file_enabled = true # write in file
file = app.log # logging filename
max_file_size = 10485760
backup_count = 5